#
# scrutinizer-ci.com Configuration File
#
# https://scrutinizer-ci.com/docs/
#

filter:
    excluded_paths:
        - 'vendor/*'
before_commands:
    - 'composer self-update'
tools:
    # disable copy paste detector and simliarity analyzer
    # because huge number of false-positives and no real value
    php_cpd: false
    php_sim: false
    # enable external code coverage (we send from travis)
    external_code_coverage: true
    php_changetracking:
        enabled: true
        bug_patterns:
            - '\bfix(?:es|ed)?\b'
        feature_patterns:
            - '\badd(?:s|ed)?\b'
            - '\bimplement(?:s|ed)?\b'
        filter:
            excluded_paths:
                - 'vendor/*'
    php_pdepend:
        enabled: true
        configuration_file: null
        suffixes:
            - php
        filter:
            excluded_paths:
                - 'vendor/*'
    php_analyzer:
        enabled: true
        config:
            metrics_coupling:
                enabled: true
            metrics_lack_of_cohesion_methods:
                enabled: true
            use_statement_fixes:
                remove_unused: true
                preserve_multiple: false
                preserve_blanklines: true
                order_alphabetically: true
                enabled: true
            doc_comment_fixes:
                enabled: true
            basic_semantic_checks:
                enabled: true
                property_on_interface: true
                missing_abstract_methods: true
        extensions:
            - php
        filter:
            excluded_paths:
                - 'vendor/*'
    php_cs_fixer:
        enabled: true
        config:
            fixers:
                indentation: true
                linefeed: true
                trailing_spaces: true
                unused_use: false
                phpdoc_params: false
                visibility: false
                return: false
                short_tag: true
                braces: false
                include: false
                php_closing_tag: true
                extra_empty_lines: true
                controls_spaces: false
                elseif: false
                eof_ending: true
            level: custom
        extensions:
            - php
        filter:
            excluded_paths:
                - 'vendor/*'