language: php

php:
  #- 5.3
  #- 5.4
  - 5.5

services:
  - mongodb
  - memcache

before_script:
   # install apt-fast to speedup later dependency installation
    - sudo add-apt-repository -y ppa:apt-fast/stable
    - sudo apt-get update
    - sudo apt-get install apt-fast
   # use apt-fast for installation of dependencies
    - sudo apt-fast -y update
  # Mongo
    #- pecl -q install mongo-1.4.1 && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  # Composer (PHP dependency solver)
    - composer self-update
    - composer install --dev --prefer-dist --no-interaction
  # X Virtual Frame Buffer
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
  # Google Chrome Browser
    #- wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
    #- sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
    #- sudo apt-get update
    #- sudo apt-get install google-chrome-stable
  # Google Chromium Browser
    #- sudo apt-get install chromium-browser chromium-browser-l10n
  # Chrome Browser Driver
    - "wget http://chromedriver.storage.googleapis.com/2.7/chromedriver_linux64.zip && unzip chromedriver_linux64.zip && sudo mv chromedriver /usr/bin"
  # Firefox
    - sudo apt-fast -m -y install firefox
  # Selenium
    - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.37.0.jar
    #- "java -jar selenium-server-standalone-2.37.0.jar -Dwebdriver.chrome.bin=/usr/bin/chromedriver > /dev/null &"
    - java -jar selenium-server-standalone-2.37.0.jar -Dwebdriver.firefox.driver=firefox > /dev/null &
    - sleep 5
  # Nginx
    - sudo apt-fast -y install nginx
    - sudo cp /home/travis/build/WPN-XM/webinterface/tests/nginx.conf.travis /etc/nginx/nginx.conf
  # PHP-FPM
    - sudo apt-fast -m -y install php5-fpm
  # Return to project root, create error.log and start Nginx
    - cd /home/travis/build/WPN-XM/webinterface
    - sudo /etc/init.d/nginx restart
    - sleep 2
    - curl http://localhost:80/ -v

script:
#  - ./bin/behat --config ./tests/behat.yml  # run behat
   - phpunit -c ./tests/phpunit.xml.travis   # run phpunit

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#koch"
    use_notice: true

# reduce commit history of git checkout
git:
  depth: 1