language: php

php:
  #- 5.3
  #- 5.4
  - 5.5

services:
   - mongodb
   - memcache

before_script:   
  # Mongo
    #- pecl -q install mongo-1.4.1 && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  # Composer (PHP dependency solver)
    - composer self-update
    - composer install --dev --prefer-dist --no-interaction
  # X Virtual Frame Buffer
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
  # Chrome Browser
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
    - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
    - sudo apt-get update
    - sudo apt-get install google-chrome-stable
  # Chrome Browser Driver
    - "wget http://chromedriver.googlecode.com/files/chromedriver_linux64_2.1.zip && unzip chromedriver_linux64_2.1.zip && sudo mv chromedriver /usr/bin"
  # Firefox
    - sudo apt-get install firefox
  # Selenium
    - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.33.0.jar
    - "java -Dwebdriver.chrome.driver=/usr/bin/chromedriver -jar selenium-server-standalone-2.33.0.jar > /dev/null &"
    - sleep 5
  # Nginx
    - "wget http://nginx.org/download/nginx-1.5.2.tar.gz && tar xvzf nginx-1.5.2.tar.gz"
    - "cd nginx-1.5.2 && ./configure --with-http_ssl_module --with-http_stub_status_module && sudo make -j8 && sudo make install"
    - "sudo cp /usr/local/nginx/sbin/nginx /usr/sbin/ && sudo mkdir /var/log/nginx/ && sudo useradd nginx"
    - "sudo mkdir /home/travis/build/WPN-XM/webinterface/nginx-1.5.2/logs && sudo touch /home/travis/build/WPN-XM/webinterface/nginx-1.5.2/logs/error.log" 
    - sudo nginx -c /home/travis/build/WPN-XM/webinterface/tests/nginx.conf.travis -p "$PWD/"
    - sleep 3
  # GO HOME
    - cd /home/travis/build/WPN-XM/webinterface

script:
#  - ./bin/behat --config ./tests/behat.yml  # run behat
   - phpunit -c ./tests/phpunit.xml.travis   # run phpunit

notifications:
  irc: "irc.freenode.org#koch"
  email: false

# reduce commit history of git checkout
git:
  depth: 30 