language: php

php: [5.6, 7.0]

cache:
  directory:
    - $HOME/.composer/cache/files

addons:
  apt:
    packages:
      - parallel
      - firefox
      - nginx
      - php5-fpm
      - php5-cli

before_script:
  # install apt-fast to speedup dependency installation
  #  - sudo add-apt-repository -y ppa:apt-fast/stable
  #  - sudo apt-get update
  #  - sudo apt-get install apt-fast
  #  - sudo apt-fast -y update
  # install dependencies
  #  - sudo apt-fast -m -y install firefox nginx php5-fpm php5-cli
  # fix folder permissions
    - chmod 777 /home/travis/build/WPN-XM/webinterface/data/
  # Composer (PHP dependency solver)
    - composer self-update
    - composer install --prefer-dist --no-interaction --optimize-autoloader
  # copy "default configs" from "vendor/wpnxm-software" repo to "default location"
    - sudo ls -alh $TRAVIS_BUILD_DIR/vendor/*
    - sudo ls -alh $TRAVIS_BUILD_DIR/vendor/wpn-xm/software/nginx/config/*
    - mkdir -p bin/nginx/
    - cp -r vendor/wpn-xm/software/nginx/config bin/nginx/
    #- cat $TRAVIS_BUILD_DIR/bin/nginx/conf/nginx.conf
    - sudo ls -alh $TRAVIS_BUILD_DIR/bin/nginx/*
  # X Virtual Frame Buffer (for Selenium)
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
  # Selenium
    - wget http://selenium-release.storage.googleapis.com/2.48/selenium-server-standalone-2.48.2.jar
    - java -jar selenium-server-standalone-2.48.2.jar > /dev/null 2> /tmp/selenium_output.log &
    - sleep 4
  # PHP-FPM
    - sudo cp $TRAVIS_BUILD_DIR/tests/travis/php-fpm.conf ~/.phpenv/versions/$(phpenv version-name)/etc/
    - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
    #- sudo service php5-fpm restart
  # Nginx
    - sudo cp $TRAVIS_BUILD_DIR/tests/travis/nginx.conf /etc/nginx/nginx.conf
    - sudo service nginx restart
    - sleep 2
    - curl http://localhost:80/ -v

script:
  # PHP lint
  - >
    echo;
    echo "Running PHP lint";
    find . -name \*.php ! -path "./vendor/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
  # PHPUnit
  - phpunit -c ./tests/phpunit.xml.travis

after_script:
  # coding style
  - php vendor/bin/php-cs-fixer --diff --dry-run -v fix
  # show nginx logs
  - cat /var/log/nginx/access.log
  - cat /var/log/nginx/error.log
  # show selenium logs
  - cat /tmp/selenium_output.log
  # upload code coverage to scrutinizer
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover $TRAVIS_BUILD_DIR/logs/clover.xml

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#koch"
    use_notice: true

git:
  depth: 10