language: php

php: [5.5, 5.6, 7.0]

cache:
  directory:
    - $HOME/.composer/cache/files

services:
  #- mongodb
  #- memcache

before_script:
   # install apt-fast to speedup dependency installation
    - sudo add-apt-repository -y ppa:apt-fast/stable
    - sudo apt-get update
    - sudo apt-get install apt-fast
    - sudo apt-fast -y update
  # install dependencies
    - sudo apt-fast -m -y install firefox nginx php5-fpm php5-cli
  # fix folder permissions
    - chmod 777 /home/travis/build/WPN-XM/webinterface/data/
  # Composer (PHP dependency solver)
    - composer self-update
    - composer install --prefer-dist --no-interaction --optimize-autoloader
  # X Virtual Frame Buffer (for Selenium)
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
  # Selenium
    - wget http://selenium-release.storage.googleapis.com/2.48/selenium-server-standalone-2.48.2.jar
    - java -jar selenium-server-standalone-2.48.2.jar > /dev/null 2> /tmp/selenium_output.log &
    - sleep 4
  # Nginx
    - sudo cp /home/travis/build/WPN-XM/webinterface/tests/nginx.conf.travis /etc/nginx/nginx.conf
    - sudo service php5-fpm restart
    - sudo service nginx restart
    #- sudo /etc/init.d/nginx restart
    - sleep 2
    - curl http://localhost:80/ -v

script:
   - phpunit -c ./tests/phpunit.xml.travis

after_script:
  # show nginx logs
  - cat /var/log/nginx/access.log
  - cat /var/log/nginx/error.log
  # show selenium logs
  - cat /tmp/selenium_output.log
  # upload code coverage to scrutinizer
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover /home/travis/build/WPN-XM/webinterface/logs/clover.xml

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#koch"
    use_notice: true

git:
  depth: 10