language: php

php: [5.5, 5.6, 7.0]

cache:
  directory:
    - $HOME/.composer/cache/files

services:
  #- mongodb
  #- memcache

before_script:
   # install apt-fast to speedup later dependency installation
    - sudo add-apt-repository -y ppa:apt-fast/stable
    - sudo apt-get update
    - sudo apt-get install apt-fast
   # use apt-fast for installation of dependencies
    - sudo apt-fast -y update
  # Mongo
    #- pecl -q install mongo-1.4.1 && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  # Composer (PHP dependency solver)
    - composer self-update
    - composer install --dev --prefer-dist --no-interaction --optimize-autoloader
  # X Virtual Frame Buffer
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
  # Firefox
    - sudo apt-fast -m -y install firefox
  # Selenium
    - wget http://selenium-release.storage.googleapis.com/2.48/selenium-server-standalone-2.48.2.jar
    - java -jar selenium-server-standalone-2.48.2.jar > /dev/null 2>&1 &
    - sleep 5
  # Nginx
    - sudo apt-fast -y install nginx
    - sudo cp /home/travis/build/WPN-XM/webinterface/tests/nginx.conf.travis /etc/nginx/nginx.conf
  # PHP-FPM
    - sudo apt-fast -m -y install php5-fpm
    - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  # fix folder permissions
    - chmod 777 /home/travis/build/WPN-XM/webinterface/php/data/
  # Return to project root, create error.log and start Nginx
    - cd /home/travis/build/WPN-XM/webinterface
    - sudo /etc/init.d/nginx restart
    - sleep 2
    - curl http://localhost:80/ -v

script:
#  - ./bin/behat --config ./tests/behat.yml
   - phpunit -c ./tests/phpunit.xml.travis

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover /home/travis/build/WPN-XM/webinterface/logs/clover.xml

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#koch"
    use_notice: true

# reduce commit history of git checkout
git:
  depth: 10
