language: php

php:
  - 5.3
  - 5.4
  - 5.5

services:
   - mongodb

before_script:
  - pecl -q install mongo-1.3.4 && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`