language: php

php:
  #- 5.3
  #- 5.4
  - 5.5

services:
  - mongodb
  - memcache

before_script:   
  # Mongo
    #- pecl -q install mongo-1.4.1 && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  # Composer (PHP dependency solver)
    - composer self-update
    - composer install --dev --prefer-dist --no-interaction
  # X Virtual Frame Buffer
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
  # Google Chrome Browser
    #- wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
    #- sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
    #- sudo apt-get update
    #- sudo apt-get install google-chrome-stable
  # Google Chromium Browser
    #- sudo apt-get update
    #- sudo apt-get install chromium-browser chromium-browser-l10n
  # Chrome Browser Driver
    #- "wget http://chromedriver.googlecode.com/files/chromedriver_linux64_2.1.zip && unzip chromedriver_linux64_2.1.zip && sudo mv chromedriver /usr/bin"
  # Firefox
    - sudo apt-get install firefox
  # Selenium
    - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.33.0.jar
    #- "java -Dwebdriver.chrome.driver=/usr/bin/chromedriver -jar selenium-server-standalone-2.33.0.jar > /dev/null &"
    - "java -Dwebdriver.firefox.driver=/usr/bin/firefox -jar selenium-server-standalone-2.33.0.jar > /dev/null &"
    - sleep 5
  # Nginx
    - sudo apt-get install nginx 
    - sudo cp /home/travis/build/WPN-XM/webinterface/tests/nginx.conf.travis /etc/nginx/nginx.conf
  # PHP-FPM
    - sudo apt-get install php5-fpm
  # Return to project root, create error.log and start Nginx
    - cd /home/travis/build/WPN-XM/webinterface
    - sudo /etc/init.d/nginx restart
    - sleep 3
    - curl http://localhost:80/ -v
    - sudo /sbin/ifconfig eth0 | grep 'inet addr:'

script:
#  - ./bin/behat --config ./tests/behat.yml  # run behat
   - phpunit -c ./tests/phpunit.xml.travis   # run phpunit

notifications:
  email: false
  irc: 
    channels: 
      - "irc.freenode.org#koch"
    use_notice: true  

# reduce commit history of git checkout
git:
  depth: 1