language: php

php:
  #- 5.3
  #- 5.4
  - 5.5

services:
   - mongodb
   - memcache

before_script:
  # Mongo
    #- pecl -q install mongo-1.4.1 && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

  # Composer (PHP dependency solver)
    - composer self-update
    - composer install --dev --prefer-dist --no-interaction

  # X Virtual Frame Buffer
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
  # Selenium
    - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.33.0.jar
    - "java -jar selenium-server-standalone-2.33.0.jar > /dev/null &"
    - sleep 5
  # Chrome Browser Engine
    - "wget -q -O- http://chromedriver.googlecode.com/files/chromedriver_linux32_2.1.zip | funzip > /usr/bin/chromedriver && chmod +x /usr/bin/chromedriver"
  # Nginx
    - "wget http://nginx.org/download/nginx-1.5.2.tar.gz && tar xvzf nginx-1.5.2.tar.gz"
    - "cd nginx-1.5.2 && ./configure --with-http_ssl_module --with-http_stub_status_module && sudo make && sudo make install"
    - "sudo cp /usr/local/nginx/sbin/nginx /usr/sbin/ && sudo mkdir /var/log/nginx/ && sudo useradd nginx"
    - sudo nginx -c tests/nginx.conf.travis -p "$PWD/"
    - sleep 3

script:
#  - ./bin/behat --config application/tests/behat.yml  # run behat
   - phpunit -c ./tests/phpunit.xml.travis             # run phpunit

notifications:
  irc: "irc.freenode.org#koch"
  email: false

# reduce commit history of git checkout
git:
  depth: 30 